accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns = [
    # 유저 목록
    path('', views.index, name='index'),
    # 회원가입
    path('signup/', views.signup, name='signup'),
    # 로그인
    path('login/', views.login, name='login'),
    # 로그아웃
    path('logout/', views.logout, name='logout'),
    # 유저 상세보기
    path('<int:user_pk>/', views.detail, name='detail'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/reviews/new/', views.review_create, name='review_create'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# User 모델을 Customizing 한다.
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='followings'
    )

movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=20)


class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(Genre, related_name='movies')
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_movies')


class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()  # return User
        fields = ('email', 'first_name', 'last_name')


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # accounts.User
        fields = UserCreationForm.Meta.fields + ('email',)

movies/forms.py
from django import forms
from .models import Movie, Review


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['content', 'score', ]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import *
from .forms import *
# from django.contrib.auth.models import User
# settings.AUTH_USER_MODEL 에 명시된 User 모델을 가져온다.
from django.contrib.auth import get_user_model

User = get_user_model()

# 유저 목록
# AttributeError at /accounts/ 남
def index(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'accounts/index.html', context)

# 회원가입
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


# 로그인
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
        return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

# 유저 상세보기
def detail(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Movie, Genre, Review
from .forms import ReviewForm


# 영화 목록
@require_GET
def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)


# 영화 상세 정보
@require_GET
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_form = ReviewForm()
    reviews = movie.reviews.all()
    context = {
        'movie': movie,
        'review_form': review_form,
        'reviews': reviews
    }
    return render(request, 'movies/detail.html', context)


# 댓글 생성
@require_POST
def review_create(request, movie_pk):
    if request.user.is_authenticated:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie_id = movie_pk
            review.user = request.user
            review.save()
            return redirect('movies:detail', movie_pk)
    return redirect('movies:index')


# 댓글 삭제
@require_POST
def review_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if review.user == request.user:
            review.delete()
        return redirect('movies:detail', movie_pk)
    return HttpResponse('You are Unauthorized', status=401)


def like(request, movie_pk):
    user = request.user
    movie = get_object_or_404(Movie, pk=movie_pk)
    if user in movie.liked_users.all():
        user.liked_movies.remove(movie)
    else:
        user.liked_movies.add(movie)
    return redirect('movies:detail', movie_pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block container %}


{% comment %} 
1. (필수) 해당 유저가 작성한 평점 정보가 모두 출력됩니다.
2. (필수) 해당 유저가 좋아하는 영화 정보가 모두 출력됩니다.
3. (필수) 해당 유저를 팔로우 한 사람의 수, 팔로잉 한 사람의 수가 출력됩니다. 
{% endcomment %}
<h2>{{ user.username }}</h2>
{% with followings=user.followings.all followers=user.followers.all%}
  <p class="lead">
    팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
  </p>
{% endwith %}


{% if user.liked_movies.all %}
  {% for movie in user.liked_movies.all %}
  <hr>
    <p>제목: {{ movie.title }}</p>
    <p>영화설명: {{ movie.description }}</p>
    {% comment %} <p>영화평점: {{ movie.score }}</p> {% endcomment %}

  {% endfor %}
{% else %}
  <span>남긴 영화리뷰가 없습니다.</span>
{% endif %}
<br>


{% endblock container %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block container %}
  <form action="{% url 'accounts:signup' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">제출하기</button>
  </form>
{% endblock container %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block container %}

{% for user in users %}
  <ul>
    <a href="{% url 'accounts:detail' user.pk %}">
      {{ user.username }}
    </a>
  </ul>
{% endfor %}

{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block container %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">제출하기</button>
  </form>
{% endblock container %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block container %}
<h2>{{ movie.title }}</h2>
<p>누적 관객 수 : {{ movie.audience }}</p>

<p>장르 : {% for genre in movie.genres.all %}<span>{{ genre.name }}</span>{% endfor %}</p>
<a href="{% url 'movies:like' movie.pk %}">
  {% if user in movie.liked_users.all %}
  <i class="fas fa-heart fa-lg" style="color: red"></i>
  {% else %}
  <i class="far fa-heart fa-lg" style="color: red"></i>
  {% endif %}
</a>
<span>{{ movie.liked_users.all | length }}명이 이 영화를 좋아합니다.</span>
<hr/>
{{ movie.description }}
<hr/>

<h3>평가</h3>
<ul>
  {% for review in reviews %}
    <li>
      <span>★{{ review.score }} | {{ review.content }}</span>
      {% if request.user == review.user %}
        <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="post">
          {% csrf_token %}
          <button type="submit">삭제하기</button>
        </form>
      {% endif %}
    </li>
  {% endfor %}
</ul>

{% if user.is_authenticated %}
  <form action="{% url 'movies:review_create' movie.pk %}" method="post">
    {% csrf_token %}
    {{ review_form.as_table }}
    <button type="submit">작성하기</button>
  </form>
{% endif %}

<br/>
<br/>
<a href="{% url 'movies:index' %}">돌아가기</a>
{% endblock container %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block title %}
<h2>Movie List</h2>
{% endblock title %}

{% block container %}
{% for movie in movies %}
<div>
  <h3>{{ movie.pk }}. {{ movie.title }}</h3>
  <a href="{% url 'movies:detail' movie.pk %}">
    <img src="{{ movie.poster_url }}" alt="" width="200" height="300">
  </a>
</div>
{% endfor %}
{% endblock container %}

pjt10/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>영화 추천</title>
    <!-- Place your kit's code here -->
      <script src="https://kit.fontawesome.com/f0508c926b.js" crossorigin="anonymous"></script>
</head>
<body> 
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <br>
    <a href="{% url 'accounts:detail' user.pk %}">회원정보</a>
    <br>
    <a href="{% url 'accounts:index' %}">회원목록</a>
    <br>
    <a href="{% url 'movies:index' %}">영화목록</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <br>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <br>
    <a href="{% url 'movies:index' %}">영화목록</a>
    {% endif %}
    <a href=""></a>
    <header>
        {% comment %} <a href="{% url 'movies:index' %}">영화목록</a>
        <a href="{% url 'movies:create' %}">영화 정보 생성</a> {% endcomment %}
    </header>
    <hr>
    <div class="container">
        {% block container %}{% endblock %}
</body>
</html>